"""add purchases table

Revision ID: 703556d96684
Revises: 4be908bf9717
Create Date: 2026-09-06 14:11:59.315686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '703556d96684'
down_revision: Union[str, None] = '4be908bf9717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # `currencycode` already exists (created in the init migration) - create_type=False stops
    # SQLAlchemy from re-issuing `CREATE TYPE currencycode`, which would fail since it's already
    # there. `purchasestatus` is genuinely new here, so it's left to auto-create normally.
    op.create_table('purchases',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('currency', postgresql.ENUM('SOFT', 'HARD', name='currencycode', create_type=False), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('price_rub_kopecks', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_payment_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELED', name='purchasestatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_payment_id')
    )
    op.create_index(op.f('ix_purchases_user_id'), 'purchases', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchases_user_id'), table_name='purchases')
    op.drop_table('purchases')
    # `purchasestatus` was created solely for this table (unlike `currencycode`, reused
    # as-is above) - drop it here so downgrade fully reverses upgrade.
    op.execute('DROP TYPE IF EXISTS purchasestatus')
    # ### end Alembic commands ###
