"""index cabinet_link_tokens token_hash

Revision ID: 87036b45e827
Revises: 703556d96684
Create Date: 2026-09-06 14:41:00.152550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87036b45e827'
down_revision: Union[str, None] = '703556d96684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cabinet_link_tokens_token_hash'), 'cabinet_link_tokens', ['token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cabinet_link_tokens_token_hash'), table_name='cabinet_link_tokens')
    # ### end Alembic commands ###
